### ISSUE TITLE
Pixelation occuring when high motion in-game

### ISSUE THREAD

**Issue by guiltyswordz** [Xaymar/obs-studio_amf-encoder-plugin#254]
Hello while streaming with this plugin I am seeing pixelation occurring in my game and webcam while high motion is going on in my game. Using High Quality-Twitch presets for my settings in the encoder and streaming at 3500 bitrate 720p30fps. I've tried adjusting vbv buffer from 50% to 70%-85% but no success. b pattern is always set to 0 as well.

**system specs**
OBS 19.0.2
AMF ENCODER 2.1.6
CPU : i7 3770k
GPU : AMD R9 380 2GB [Driver : 17.5.2]
MOBO : ASrock Z68 Extreme3 Gen3
PSU : Thermal Take Bronze 650w
RAM : 16GB

**Comment by max20091** [comment]
3500 is not enough for hardware streaming, maybe 6000? Twitch is now allowed to stream up to 6 Mbps instead of 3500

**Comment by Benman2785** [comment]
well - i will upload a test video for you

but have in mind: if your webcam also captures a lot of your room you waste a lot of bandwith on that too - thats what you will see in the video uploaded in 1h ;)

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

------

Specifically you're missing log files and example video.
